[project]
name = "luma_ge"
version = "0.1.0"
description = "A Python package that serves as the geospatial engine for the Epistem Land Use Mapping for All (Luma) platform."
dependencies = [
    "pandas",
    "geopandas",
    "earthengine-api",
    "leafmap",
    "geemap",
    "numpy",
    "matplotlib",
    "seaborn",
    "altair",
    "tqdm",
    "scipy",
    "pillow",
    "shapely",
    "ipykernel",
    "streamlit_folium",
    "shapely",
    "pyshp",
    "fiona",
    "rtree",
    "spyndex>=0.9.0",
    "eemont>=0.3.0",
]
requires-python = ">=3.9"

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "pytest-mock>=3.0",
]
